# Generated by Django 4.0.4 on 2022-04-27 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanagement',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermanagement',
            name='last_name',
        ),
    ]
