# Generated by Django 4.0.4 on 2022-04-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_usermanagement_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermanagement',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
