# Generated by Django 4.0.4 on 2022-04-26 13:50

from django.db import migrations, models
import django.db.models.deletion
import tw_replica.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post_img', models.ImageField(blank=True, upload_to=tw_replica.models.post_directory_path)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usermanagement')),
            ],
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retweet_stamp', models.DateTimeField(auto_now_add=True)),
                ('retweet_text', models.TextField(blank=True, max_length=150)),
                ('tweet_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tw_replica.post')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.usermanagement')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tw_replica.post')),
                ('retweet_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tw_replica.retweet')),
            ],
        ),
    ]
